name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_UPSPLASH_KEY: ${{ secrets.REACT_APP_UPSPLASH_KEY}}
          REACT_APP_OPENWEATHERMAP_KEY: ${{ secrets.REACT_APP_OPENWEATHERMAP_KEY }}
          REACT_APP_IPDATA_KEY: ${{secrets.REACT_APP_IPDATA_KEY}}

      - name: Deploy 🚀
        uses: nostam/m7-d10-weather-app@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
